#!/usr/bin/with-contenv sh

cd $WORKDIR

exec s6-setuidgid appuser google-chrome --headless --disable-gpu --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0 --no-sandbox --disable-dev-shm-usage
